In [7]:
import numpy as np

this is a 1 dimential array

In [ ]:
a= np.array([1,2,3])
print(a)

[1 2 3]


this is a 2 dimentional array

In [6]:
b=np.array([(9,0,8,0,7,0),(6,0,5,0,4,0)])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]
